server:
  port: 8300
spring:
  profiles: dev
  application:
    name: spring-cloud-config-client-8300
eureka:
  client:
  service-url:
    defaultZone: http://eurekaserver9000.com:9000/eureka/,http://eurekaserver9001.com:9001/eureka/,http://eurekaserver9002.com:9002/eureka/

---
server:
  port: 8333
spring:
  profiles: test
  application:
    name: spring-cloud-config-client-8333
eureka:
  client:
    service-url:
       defaultZone: http://eurekaserver9000.com:9000/eureka/,http://eurekaserver9001.com:9001/eureka/,http://eurekaserver9002.com:9002/eureka/



